name: Deliver container

on: push

jobs:
  delivery:
    run-on: ubuntu-latest
    name: Deliver container job
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USER }}/python-api-devops:latest .
        
      - name: Upload container
        run: docker push ${{ secrets.DOCKER_USER }}/python-api-devops:latest
